### ISSUE TITLE
Error with npm run build

### ISSUE THREAD

**Issue by Notplayingallday383** [VyperGroup/aero#3]
so um I npm run build on the Unstable branch since it had content in the package.json folder and well its not really working. Heres the error log if you want to review it. Thanks
[webpack.error.log](https://github.com/ProxyHaven/aero/files/12558651/webpack.error.log)
Also I did run npm i if your wondering

**Comment by proudparrot2** [comment]
It’s probably because EV has ZERO webpack or vite configuration which is critical for a tool that’s supposed to be built

**Comment by proudparrot2** [comment]
I don’t know why it hasn’t been resolved yet

**Comment by MovByte** [comment]
> I don’t know why it hasn’t been resolved yet

I haven't found anyone that is able to resolve this issue. I hope it gets fixed soon

**Comment by proudparrot2** [comment]
> > It’s probably because EV has ZERO webpack or vite configuration which is critical for a tool that’s supposed to be built
> 
> This is slander check the repo

Yeah in the unstable branch which most people arent gonna check by default

**Comment by Notplayingallday383** [comment]
alr lmk if it gets fixed or if theres something I should try

**Comment by MovByte** [comment]
> > > It’s probably because EV has ZERO webpack or vite configuration which is critical for a tool that’s supposed to be built
> > 
> > 
> > This is slander check the repo
> 
> Yeah in the unstable branch which most people arent gonna check by default

They wouldn't want to use a broken proxy anyways

**Comment by MovByte** [comment]
> alr lmk if it gets fixed or if theres something I should try

The builds have been fixed now 😃
